# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34d223c26d4eae6181f3aff4b1b82839e16e8904e3cfbe39fc1972ecd7f2675e8dc7b44f7c46c928a69e9d3fe764174f7a6f651d9d400a94f2fc651f308c928

test:
  secret_key_base: 1c2e1be89b3cbef2bb92332fb6c555ce6c76b7974f2c132941f53ebc7744de15f8c0fb441d5fed738de7c65b9c0374636b618f2307a10306cb23147f0338f1d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
